version: "3.7"

services:
  db:
    build:
      context: .
      args:
        POSTGRES_DB: test
    restart: always
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
